// Database 
const SUCCESS = 'SUCCESS';
const FAIL= 'FAIL';

module.exports = Object.freeze({
	// Commom Error codes
	SUCCESS: SUCCESS,
	FAIL: FAIL,
	MISSING_MANDATORY_ATTRIBUTE: 'MISSING_MANDATORY_ATTRIBUTE',
	RECORD_NOT_FOUND: 'RECORD_NOT_FOUND',
	NOT_FOUND: 'NOT_FOUND',
	EXCEED_CHARACTER_LENGTH: 'EXCEED_CHARACTER_LENGTH',
    MAX_VALUE_EXCEED: 'MAX_VALUE_EXCEED',
	INVALID_DATA: 'INVALID_DATA',
    INVALID_EMAIL: 'INVALID_EMAIL',
    INVALID_CHARACTERS: 'INVALID_CHARACTERS',
    STATE_IDLE: 'IDLE',
    STATE_LOADING: 'LOADING',
    STATE_LOADED: 'LOADED',
    STATE_DELIVERING: 'DELIVERING',
    STATE_DELIVERED: 'DELIVERED',
    STATE_RETURNING: 'RETURNING',
    INVALID_IMAGE: 'INVALID_IMAGE',
});